import { ApprovedTable } from "../types";

export const APPROVED_SCHEMA: ApprovedTable[] = [
  {
    tableName: "orders",
    displayName: "Sales Orders",
    description: "Transactional order records detailing revenue, payment methods, status, and dates.",
    category: "Transactions",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Order ID", dataType: "INTEGER", description: "Unique identifier for the order", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "customer_id", displayName: "Customer ID", dataType: "INTEGER", description: "Reference to the customer placing order", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "order_date", displayName: "Order Date", dataType: "DATE", description: "Timestamp when the order was placed (YYYY-MM-DD)", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"], exampleValues: ["2025-01-15", "2025-06-20"] },
      { name: "status", displayName: "Order Status", dataType: "TEXT", description: "State of order processing: Completed, Shipped, Processing, Refunded", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"], exampleValues: ["Completed", "Shipped"] },
      { name: "total_amount", displayName: "Total Revenue ($)", dataType: "REAL", description: "Net revenue amount generated by the order in USD", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "discount_amount", displayName: "Discount ($)", dataType: "REAL", description: "Applied promotional discounts", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "payment_method", displayName: "Payment Method", dataType: "TEXT", description: "Payment mode: Credit Card, Wire Transfer, ACH, Corporate PO", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "billing_cycle", displayName: "Billing Cycle", dataType: "TEXT", description: "Annual or Monthly subscription schedule", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
  {
    tableName: "customers",
    displayName: "Customer Directory",
    description: "Profiles of corporate and individual buyers, tier classifications, and segments.",
    category: "Master Data",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Customer ID", dataType: "INTEGER", description: "Unique customer identifier", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "name", displayName: "Contact Name", dataType: "TEXT", description: "Full name of the primary contact", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "company", displayName: "Company Name", dataType: "TEXT", description: "Registered enterprise or organization name", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "email", displayName: "Email Address", dataType: "TEXT", description: "Corporate contact email", allowedRoles: ["ADMIN", "ANALYST"] }, // Masked for viewers
      { name: "region_id", displayName: "Region ID", dataType: "INTEGER", description: "Geographical region link", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "segment", displayName: "Market Segment", dataType: "TEXT", description: "Target segment: Enterprise, Mid-Market, SMB, Startup", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "tier", displayName: "Customer Tier", dataType: "TEXT", description: "Service tier: Platinum, Gold, Silver", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "lifetime_value", displayName: "Lifetime Value (LTV)", dataType: "REAL", description: "Cumulative calculated historical spend", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "created_at", displayName: "Sign Up Date", dataType: "DATE", description: "Date customer registered in system", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
  {
    tableName: "products",
    displayName: "Product Catalog",
    description: "Catalog of software modules, subscription tiers, and hardware solutions.",
    category: "Master Data",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Product ID", dataType: "INTEGER", description: "Unique product identifier", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "name", displayName: "Product Name", dataType: "TEXT", description: "Commercial title of product or license", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "category", displayName: "Category", dataType: "TEXT", description: "Classification: Cloud Platform, AI Suite, Analytics Pro, Security Guard, Data Connect", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "price", displayName: "Retail Price ($)", dataType: "REAL", description: "Official list price in USD", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "unit_cost", displayName: "Unit Cost ($)", dataType: "REAL", description: "Internal procurement/COGS cost (Sensitive)", isSensitive: true, allowedRoles: ["ADMIN"] }, // ADMIN only!
      { name: "stock_status", displayName: "Availability", dataType: "TEXT", description: "Available, In Stock, Limited", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "sku", displayName: "Stock Keeping Unit", dataType: "TEXT", description: "Inventory identification code", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
  {
    tableName: "order_items",
    displayName: "Order Line Items",
    description: "Granular product quantities and subtotals per order.",
    category: "Transactions",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Line Item ID", dataType: "INTEGER", description: "Unique line item identifier", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "order_id", displayName: "Order ID", dataType: "INTEGER", description: "Associated order ID", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "product_id", displayName: "Product ID", dataType: "INTEGER", description: "Associated product ID", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "quantity", displayName: "Quantity", dataType: "INTEGER", description: "Number of units purchased", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "unit_price", displayName: "Unit Price ($)", dataType: "REAL", description: "Price charged per unit", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "subtotal", displayName: "Subtotal ($)", dataType: "REAL", description: "Total price for the line item", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
  {
    tableName: "regions",
    displayName: "Geographic Regions",
    description: "Geographic operational territories and regional leadership assignments.",
    category: "Master Data",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Region ID", dataType: "INTEGER", description: "Unique region code", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "name", displayName: "Region Name", dataType: "TEXT", description: "Name of region: North America, Europe, Asia Pacific, Latin America, Middle East", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "country", displayName: "Primary Country", dataType: "TEXT", description: "Lead jurisdiction or regional headquarters", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "regional_manager", displayName: "Regional Manager", dataType: "TEXT", description: "Director overseeing territorial operations", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "quarterly_target", displayName: "Target Goal ($)", dataType: "REAL", description: "Quarterly sales revenue target quota", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
  {
    tableName: "marketing_campaigns",
    displayName: "Marketing Campaigns",
    description: "Performance metrics for omni-channel acquisition and digital advertising.",
    category: "Marketing",
    allowedRoles: ["ADMIN", "ANALYST", "VIEWER"],
    columns: [
      { name: "id", displayName: "Campaign ID", dataType: "INTEGER", description: "Unique campaign identifier", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "name", displayName: "Campaign Name", dataType: "TEXT", description: "Title of marketing initiative", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "channel", displayName: "Marketing Channel", dataType: "TEXT", description: "Search Ads, LinkedIn B2B, Content Marketing, Partner Summit, Webinar", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "budget", displayName: "Allocated Budget ($)", dataType: "REAL", description: "Approved budget allocation", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "spend", displayName: "Actual Spend ($)", dataType: "REAL", description: "Realized spend to date", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "conversions", displayName: "Conversions", dataType: "INTEGER", description: "Total qualified lead conversions", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "revenue_generated", displayName: "Generated Revenue ($)", dataType: "REAL", description: "Direct attributed revenue from campaign", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "start_date", displayName: "Start Date", dataType: "DATE", description: "Launch date", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
      { name: "end_date", displayName: "End Date", dataType: "DATE", description: "End date", allowedRoles: ["ADMIN", "ANALYST", "VIEWER"] },
    ],
  },
];

export function getApprovedTablesForRole(role: string): ApprovedTable[] {
  return APPROVED_SCHEMA.filter((table) => table.allowedRoles.includes(role as any)).map((table) => ({
    ...table,
    columns: table.columns.filter((col) => col.allowedRoles.includes(role as any)),
  }));
}

export function isTableApproved(tableName: string, role: string = "VIEWER"): boolean {
  const norm = tableName.toLowerCase().trim();
  const table = APPROVED_SCHEMA.find((t) => t.tableName.toLowerCase() === norm);
  if (!table) return false;
  return table.allowedRoles.includes(role as any);
}

export function isColumnApproved(tableName: string, columnName: string, role: string = "VIEWER"): boolean {
  const normTable = tableName.toLowerCase().trim();
  const normCol = columnName.toLowerCase().trim();
  const table = APPROVED_SCHEMA.find((t) => t.tableName.toLowerCase() === normTable);
  if (!table) return false;
  const col = table.columns.find((c) => c.name.toLowerCase() === normCol);
  if (!col) return false;
  return col.allowedRoles.includes(role as any);
}
